name: ThingsDemo UI and API tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  run-pytest:
    runs-on: ubuntu-latest
    env:
      JWT_TOKEN: ${{ secrets.JWT_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API and Model tests
        run: |
          pytest --html=report_api.html test_api_telemetry.py
          pytest --html=report_model.html test_model_output.py

      - name: Run UI Tests
        run:
          python test_dashboard_ui.py

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: |
            report_api.html
            report_model.html